const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.NodeWebkit,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.Internationalization,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimRepeatToFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetZElevation,
		C3.Plugins.Text.Cnds.OnDestroyed,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Button.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.Seek
	];
};
self.C3_JsPropNameTable = [
	{X_Pos: 0},
	{Y_Pos: 0},
	{X_Pos1: 0},
	{Y_Pos1: 0},
	{"8Direction": 0},
	{СледитьЗа: 0},
	{Kolya: 0},
	{Keyboard: 0},
	{Solid: 0},
	{Adann: 0},
	{PressE: 0},
	{Якорь: 0},
	{Ramka1: 0},
	{Ramka2: 0},
	{AdannsFace: 0},
	{Текст: 0},
	{Угасание: 0},
	{Текст2: 0},
	{Pol: 0},
	{Твёрдый: 0},
	{Stenaopenvent: 0},
	{Stena: 0},
	{Stenalockvent: 0},
	{Table: 0},
	{InvisebleBlock: 0},
	{Stenawithcamera: 0},
	{Текст3: 0},
	{StenaBokovaya1: 0},
	{StenaBokovaya2: 0},
	{Elevatore: 0},
	{Door: 0},
	{Door2: 0},
	{Stena2: 0},
	{Menu: 0},
	{BlackScreen: 0},
	{MenuText: 0},
	{MenuText2: 0},
	{Мышь: 0},
	{Браузер: 0},
	{Play: 0},
	{Creators: 0},
	{Exit: 0},
	{Текст4: 0},
	{Creators2: 0},
	{MenuText3: 0},
	{Back: 0},
	{Controls: 0},
	{Cursor: 0},
	{Текст5: 0},
	{BigDoor: 0},
	{Stenabokovaya3: 0},
	{Stenabokovaya4: 0},
	{Stena3: 0},
	{Stena4: 0},
	{Stena5: 0},
	{FonLab: 0},
	{Grass1: 0},
	{Tropa: 0},
	{Grass2: 0},
	{Grass3: 0},
	{Stone1: 0},
	{Stone2: 0},
	{Tree: 0},
	{KolyaFace: 0},
	{PressEdoor1: 0},
	{Текст6: 0},
	{MenuText4: 0},
	{MenuText5: 0},
	{BlackScreen1: 0},
	{BlackScreen2: 0},
	{Skafchik: 0},
	{Table2: 0},
	{Papers: 0},
	{Blood: 0},
	{Table3: 0},
	{PressEdoor2: 0},
	{Adann2: 0},
	{Next1: 0},
	{Next2: 0},
	{Close: 0},
	{Next3: 0},
	{Door1: 0},
	{Door3: 0},
	{PressEdoor3: 0},
	{PressEdoor4: 0},
	{PressEdoor5: 0},
	{PressEdoor6: 0},
	{PressEdoor7: 0},
	{LiftBlocker: 0},
	{DoorBlocker: 0},
	{PressEdoor8: 0},
	{PressEdoor9: 0},
	{DoorBlocker1: 0},
	{DoorBlocker2: 0},
	{PressEdoor10: 0},
	{DoorBlocker3: 0},
	{PressEdoor11: 0},
	{DoorBlocker4: 0},
	{PressEdoor12: 0},
	{DoorBlocker5: 0},
	{PressEdoor13: 0},
	{DoorBlocker6: 0},
	{PressEdoor14: 0},
	{DoorBlocker7: 0},
	{PressEdoor15: 0},
	{DoorBlocker8: 0},
	{PressEdoor16: 0},
	{DoorBlocker9: 0},
	{PressEdoor17: 0},
	{DoorBlocker10: 0},
	{PressEdoor18: 0},
	{DoorBlocker11: 0},
	{PressEdoor19: 0},
	{DoorBlocker12: 0},
	{PressEdoor20: 0},
	{DoorBlocker13: 0},
	{PressEdoor21: 0},
	{DoorBlocker14: 0},
	{PressEdoor22: 0},
	{DoorBlocker15: 0},
	{PressEdoor23: 0},
	{DoorBlocker16: 0},
	{DoorBlocker17: 0},
	{DoorBlocker18: 0},
	{DoorBlocker19: 0},
	{DoorBlocker20: 0},
	{PressEdoor24: 0},
	{DoorBlocker21: 0},
	{PressEdoor25: 0},
	{DoorBlocker22: 0},
	{PressEdoor26: 0},
	{DoorBlocker23: 0},
	{DoorBlocker24: 0},
	{PressEdoor27: 0},
	{DoorBlocker25: 0},
	{PressEdoor28: 0},
	{DoorBlocker26: 0},
	{PressEdoor29: 0},
	{DoorBlocker27: 0},
	{Аудио: 0},
	{Logo: 0},
	{DoorBlocker28: 0},
	{PressEdoor30: 0},
	{Next4: 0},
	{Next5: 0},
	{Stenawithwindow: 0},
	{Polka: 0},
	{Table4: 0},
	{Table5: 0},
	{Stremyanka1: 0},
	{Ramka3: 0},
	{Otvertka: 0},
	{Ramka4: 0},
	{Stremyanka2: 0},
	{InvisibleBlock2: 0},
	{Katscene1: 0},
	{Enteratwrongplace: 0},
	{Hmzw_Bpzmm_Nwcz: 0},
	{Hmzw_Bpzmm_Nwcz_Face: 0},
	{Hmzw_Bpzmm_Nwcz_Scream: 0},
	{Hmzw_Wvm_Bpzmm: 0},
	{Book: 0},
	{Hmzw_Wvm_Bpzmm2: 0},
	{File1: 0},
	{Trigger: 0},
	{ChildrensHome: 0},
	{Road: 0},
	{Tropa2: 0},
	{Tropa3: 0},
	{Tree2: 0},
	{Peni: 0},
	{kust: 0},
	{Fon1: 0},
	{Fon2: 0},
	{Logo2: 0},
	{Tropa4: 0},
	{Fon3: 0},
	{kust2: 0},
	{File2: 0},
	{Close1: 0},
	{Close2: 0},
	{PressEdoor31: 0},
	{Trigger1: 0},
	{Fon4: 0},
	{Tree3: 0},
	{Katscene2: 0},
	{Next6: 0},
	{Next7: 0},
	{Next8: 0},
	{Next9: 0},
	{Next10: 0},
	{Next11: 0},
	{Next12: 0},
	{Next13: 0},
	{Next14: 0},
	{Next15: 0},
	{Next16: 0},
	{Next17: 0},
	{Next18: 0},
	{Next19: 0},
	{Next20: 0},
	{Next21: 0},
	{Next22: 0},
	{Next23: 0},
	{Next24: 0},
	{Next25: 0},
	{Next26: 0},
	{Next27: 0},
	{Next28: 0},
	{Next29: 0},
	{Next30: 0},
	{Next31: 0},
	{Next32: 0},
	{Next33: 0},
	{Next34: 0},
	{Next35: 0},
	{Next36: 0},
	{Next37: 0},
	{Next38: 0},
	{Next39: 0},
	{Next40: 0},
	{PressE1: 0},
	{Close3: 0},
	{Doors: 0},
	{Name: 0},
	{Leave: 0},
	{Next41: 0},
	{Next42: 0},
	{Next43: 0},
	{Next44: 0},
	{Next45: 0},
	{Next46: 0},
	{Next47: 0},
	{Next48: 0},
	{Next49: 0},
	{Next50: 0},
	{Katscene3: 0},
	{Katscene4: 0},
	{Next51: 0},
	{Next52: 0},
	{Next53: 0},
	{Next54: 0},
	{Next55: 0},
	{Next56: 0},
	{Next57: 0},
	{Next58: 0},
	{Next59: 0},
	{Next60: 0},
	{Katscene5: 0},
	{Katscene6: 0},
	{Next61: 0},
	{Next62: 0},
	{Next63: 0},
	{Next64: 0},
	{Next65: 0},
	{Next66: 0},
	{Next67: 0},
	{Next68: 0},
	{Next69: 0},
	{Next70: 0},
	{Katscene7: 0},
	{BlackScreen3: 0},
	{Katscene8: 0},
	{Age: 0},
	{HeadScientist: 0},
	{Advisors: 0},
	{Stenabokovaya5: 0},
	{NWjs: 0},
	{Shkaf: 0},
	{Polka2: 0},
	{Polka3: 0},
	{Table6: 0},
	{Table7: 0},
	{Photo: 0},
	{Crate: 0},
	{Documents: 0},
	{Boxes: 0},
	{Тач: 0},
	{Photo1: 0},
	{ВводТекста: 0},
	{Ramka5: 0},
	{Key1: 0},
	{Key: 0},
	{Key2: 0},
	{Backtogame: 0},
	{Leave2: 0},
	{HmzwNwczNwcz: 0},
	{HmzwNwczNwczFace: 0},
	{AdannButton: 0},
	{Room: 0},
	{BrokenAdann: 0},
	{AdannBrokenFace: 0},
	{Hmzw_Wvm_Admv: 0},
	{Hmzw_Wvm_AdmvFace: 0},
	{Close4: 0},
	{Computer: 0},
	{Table8: 0},
	{Ramka6: 0},
	{SpriteNext1: 0},
	{SpriteNext2: 0},
	{SpriteBack: 0},
	{Katscene9: 0},
	{Shadow: 0},
	{SpriteNext3: 0},
	{Face: 0},
	{SpriteNext4: 0},
	{SpriteNext5: 0},
	{FilesSECRETROOM: 0},
	{FileNext1: 0},
	{FileNext2: 0},
	{FileBack: 0},
	{FileNext3: 0},
	{FileNext4: 0},
	{FileNext5: 0},
	{FileNext6: 0},
	{Katscene21: 0},
	{KatsceneSprite: 0},
	{AdannSprite: 0},
	{EchoSprite: 0},
	{EchoFace: 0},
	{KatsceneSprite2: 0},
	{EchoSprite2: 0},
	{AdannSprite2: 0},
	{KatsceneSprite3: 0},
	{AdannSprite3: 0},
	{EchoSprite3: 0},
	{KatsceneSprite4: 0},
	{KatsceneSprite5: 0},
	{EchoSprite4: 0},
	{See: 0},
	{KatsceneSprite6: 0},
	{EchoSprite5: 0},
	{KatsceneSprite7: 0},
	{EchoSprite6: 0},
	{Gone: 0},
	{DoorBlocker29: 0},
	{PressEdoor32: 0},
	{EndKatscene: 0},
	{BlackScreen4: 0},
	{EchoSprite7: 0},
	{SpriteNext6: 0},
	{KatsceneSprite8: 0},
	{SpriteNext7: 0},
	{Локализация: 0},
	{DeathKatscene1: 0},
	{DeathKatscene2: 0},
	{Reset: 0},
	{EndSprite: 0}
];

self.InstanceType = {
	Kolya: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Adann: class extends self.ISpriteInstance {},
	PressE: class extends self.ISpriteInstance {},
	Ramka1: class extends self.ISpriteInstance {},
	Ramka2: class extends self.ISpriteInstance {},
	AdannsFace: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	Pol: class extends self.ISpriteInstance {},
	Stenaopenvent: class extends self.ISpriteInstance {},
	Stena: class extends self.ISpriteInstance {},
	Stenalockvent: class extends self.ISpriteInstance {},
	Table: class extends self.ISpriteInstance {},
	InvisebleBlock: class extends self.ISpriteInstance {},
	Stenawithcamera: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	StenaBokovaya1: class extends self.ISpriteInstance {},
	StenaBokovaya2: class extends self.ISpriteInstance {},
	Elevatore: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	Door2: class extends self.ISpriteInstance {},
	Stena2: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	MenuText: class extends self.ITextInstance {},
	MenuText2: class extends self.ITextInstance {},
	Мышь: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	Play: class extends self.ISpriteInstance {},
	Creators: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {},
	Creators2: class extends self.ISpriteInstance {},
	MenuText3: class extends self.ITextInstance {},
	Back: class extends self.ISpriteInstance {},
	Controls: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Текст5: class extends self.ITextInstance {},
	BigDoor: class extends self.ISpriteInstance {},
	Stenabokovaya3: class extends self.ISpriteInstance {},
	Stenabokovaya4: class extends self.ISpriteInstance {},
	Stena3: class extends self.ISpriteInstance {},
	Stena4: class extends self.ISpriteInstance {},
	Stena5: class extends self.ISpriteInstance {},
	FonLab: class extends self.ITiledBackgroundInstance {},
	Grass1: class extends self.ITiledBackgroundInstance {},
	Tropa: class extends self.ISpriteInstance {},
	Grass2: class extends self.ISpriteInstance {},
	Grass3: class extends self.ISpriteInstance {},
	Stone1: class extends self.ISpriteInstance {},
	Stone2: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	KolyaFace: class extends self.ISpriteInstance {},
	PressEdoor1: class extends self.ISpriteInstance {},
	Текст6: class extends self.ITextInstance {},
	MenuText4: class extends self.ITextInstance {},
	MenuText5: class extends self.ITextInstance {},
	BlackScreen1: class extends self.ITiledBackgroundInstance {},
	BlackScreen2: class extends self.ITiledBackgroundInstance {},
	Skafchik: class extends self.ISpriteInstance {},
	Table2: class extends self.ISpriteInstance {},
	Papers: class extends self.ISpriteInstance {},
	Blood: class extends self.ISpriteInstance {},
	Table3: class extends self.ISpriteInstance {},
	PressEdoor2: class extends self.ISpriteInstance {},
	Adann2: class extends self.ISpriteInstance {},
	Next1: class extends self.IButtonInstance {},
	Next2: class extends self.IButtonInstance {},
	Close: class extends self.IButtonInstance {},
	Next3: class extends self.IButtonInstance {},
	Door1: class extends self.ISpriteInstance {},
	Door3: class extends self.ISpriteInstance {},
	PressEdoor3: class extends self.ISpriteInstance {},
	PressEdoor4: class extends self.ISpriteInstance {},
	PressEdoor5: class extends self.ISpriteInstance {},
	PressEdoor6: class extends self.ISpriteInstance {},
	PressEdoor7: class extends self.ISpriteInstance {},
	LiftBlocker: class extends self.ISpriteInstance {},
	DoorBlocker: class extends self.ISpriteInstance {},
	PressEdoor8: class extends self.ISpriteInstance {},
	PressEdoor9: class extends self.ISpriteInstance {},
	DoorBlocker1: class extends self.ISpriteInstance {},
	DoorBlocker2: class extends self.ISpriteInstance {},
	PressEdoor10: class extends self.ISpriteInstance {},
	DoorBlocker3: class extends self.ISpriteInstance {},
	PressEdoor11: class extends self.ISpriteInstance {},
	DoorBlocker4: class extends self.ISpriteInstance {},
	PressEdoor12: class extends self.ISpriteInstance {},
	DoorBlocker5: class extends self.ISpriteInstance {},
	PressEdoor13: class extends self.ISpriteInstance {},
	DoorBlocker6: class extends self.ISpriteInstance {},
	PressEdoor14: class extends self.ISpriteInstance {},
	DoorBlocker7: class extends self.ISpriteInstance {},
	PressEdoor15: class extends self.ISpriteInstance {},
	DoorBlocker8: class extends self.ISpriteInstance {},
	PressEdoor16: class extends self.ISpriteInstance {},
	DoorBlocker9: class extends self.ISpriteInstance {},
	PressEdoor17: class extends self.ISpriteInstance {},
	DoorBlocker10: class extends self.ISpriteInstance {},
	PressEdoor18: class extends self.ISpriteInstance {},
	DoorBlocker11: class extends self.ISpriteInstance {},
	PressEdoor19: class extends self.ISpriteInstance {},
	DoorBlocker12: class extends self.ISpriteInstance {},
	PressEdoor20: class extends self.ISpriteInstance {},
	DoorBlocker13: class extends self.ISpriteInstance {},
	PressEdoor21: class extends self.ISpriteInstance {},
	DoorBlocker14: class extends self.ISpriteInstance {},
	PressEdoor22: class extends self.ISpriteInstance {},
	DoorBlocker15: class extends self.ISpriteInstance {},
	PressEdoor23: class extends self.ISpriteInstance {},
	DoorBlocker16: class extends self.ISpriteInstance {},
	DoorBlocker17: class extends self.ISpriteInstance {},
	DoorBlocker18: class extends self.ISpriteInstance {},
	DoorBlocker19: class extends self.ISpriteInstance {},
	DoorBlocker20: class extends self.ISpriteInstance {},
	PressEdoor24: class extends self.ISpriteInstance {},
	DoorBlocker21: class extends self.ISpriteInstance {},
	PressEdoor25: class extends self.ISpriteInstance {},
	DoorBlocker22: class extends self.ISpriteInstance {},
	PressEdoor26: class extends self.ISpriteInstance {},
	DoorBlocker23: class extends self.ISpriteInstance {},
	DoorBlocker24: class extends self.ISpriteInstance {},
	PressEdoor27: class extends self.ISpriteInstance {},
	DoorBlocker25: class extends self.ISpriteInstance {},
	PressEdoor28: class extends self.ISpriteInstance {},
	DoorBlocker26: class extends self.ISpriteInstance {},
	PressEdoor29: class extends self.ISpriteInstance {},
	DoorBlocker27: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Logo: class extends self.ISpriteInstance {},
	DoorBlocker28: class extends self.ISpriteInstance {},
	PressEdoor30: class extends self.ISpriteInstance {},
	Next4: class extends self.IButtonInstance {},
	Next5: class extends self.IButtonInstance {},
	Stenawithwindow: class extends self.ISpriteInstance {},
	Polka: class extends self.ISpriteInstance {},
	Table4: class extends self.ISpriteInstance {},
	Table5: class extends self.ISpriteInstance {},
	Stremyanka1: class extends self.ISpriteInstance {},
	Ramka3: class extends self.ISpriteInstance {},
	Otvertka: class extends self.ISpriteInstance {},
	Ramka4: class extends self.ISpriteInstance {},
	Stremyanka2: class extends self.ISpriteInstance {},
	InvisibleBlock2: class extends self.ISpriteInstance {},
	Katscene1: class extends self.ISpriteInstance {},
	Enteratwrongplace: class extends self.ISpriteInstance {},
	Hmzw_Bpzmm_Nwcz: class extends self.ISpriteInstance {},
	Hmzw_Bpzmm_Nwcz_Face: class extends self.ISpriteInstance {},
	Hmzw_Bpzmm_Nwcz_Scream: class extends self.ISpriteInstance {},
	Hmzw_Wvm_Bpzmm: class extends self.ISpriteInstance {},
	Book: class extends self.ISpriteInstance {},
	Hmzw_Wvm_Bpzmm2: class extends self.ISpriteInstance {},
	File1: class extends self.ISpriteInstance {},
	Trigger: class extends self.ISpriteInstance {},
	ChildrensHome: class extends self.ISpriteInstance {},
	Road: class extends self.ISpriteInstance {},
	Tropa2: class extends self.ISpriteInstance {},
	Tropa3: class extends self.ISpriteInstance {},
	Tree2: class extends self.ISpriteInstance {},
	Peni: class extends self.ISpriteInstance {},
	kust: class extends self.ISpriteInstance {},
	Fon1: class extends self.ISpriteInstance {},
	Fon2: class extends self.ISpriteInstance {},
	Logo2: class extends self.ISpriteInstance {},
	Tropa4: class extends self.ISpriteInstance {},
	Fon3: class extends self.ISpriteInstance {},
	kust2: class extends self.ISpriteInstance {},
	File2: class extends self.ISpriteInstance {},
	Close1: class extends self.IButtonInstance {},
	Close2: class extends self.IButtonInstance {},
	PressEdoor31: class extends self.ISpriteInstance {},
	Trigger1: class extends self.ISpriteInstance {},
	Fon4: class extends self.ISpriteInstance {},
	Tree3: class extends self.ISpriteInstance {},
	Katscene2: class extends self.ISpriteInstance {},
	Next6: class extends self.IButtonInstance {},
	Next7: class extends self.IButtonInstance {},
	Next8: class extends self.IButtonInstance {},
	Next9: class extends self.IButtonInstance {},
	Next10: class extends self.IButtonInstance {},
	Next11: class extends self.IButtonInstance {},
	Next12: class extends self.IButtonInstance {},
	Next13: class extends self.IButtonInstance {},
	Next14: class extends self.IButtonInstance {},
	Next15: class extends self.IButtonInstance {},
	Next16: class extends self.IButtonInstance {},
	Next17: class extends self.IButtonInstance {},
	Next18: class extends self.IButtonInstance {},
	Next19: class extends self.IButtonInstance {},
	Next20: class extends self.IButtonInstance {},
	Next21: class extends self.IButtonInstance {},
	Next22: class extends self.IButtonInstance {},
	Next23: class extends self.IButtonInstance {},
	Next24: class extends self.IButtonInstance {},
	Next25: class extends self.IButtonInstance {},
	Next26: class extends self.IButtonInstance {},
	Next27: class extends self.IButtonInstance {},
	Next28: class extends self.IButtonInstance {},
	Next29: class extends self.IButtonInstance {},
	Next30: class extends self.IButtonInstance {},
	Next31: class extends self.IButtonInstance {},
	Next32: class extends self.IButtonInstance {},
	Next33: class extends self.IButtonInstance {},
	Next34: class extends self.IButtonInstance {},
	Next35: class extends self.IButtonInstance {},
	Next36: class extends self.IButtonInstance {},
	Next37: class extends self.IButtonInstance {},
	Next38: class extends self.IButtonInstance {},
	Next39: class extends self.IButtonInstance {},
	Next40: class extends self.IButtonInstance {},
	PressE1: class extends self.ISpriteInstance {},
	Close3: class extends self.IButtonInstance {},
	Doors: class extends self.IButtonInstance {},
	Name: class extends self.IButtonInstance {},
	Leave: class extends self.IButtonInstance {},
	Next41: class extends self.IButtonInstance {},
	Next42: class extends self.IButtonInstance {},
	Next43: class extends self.IButtonInstance {},
	Next44: class extends self.IButtonInstance {},
	Next45: class extends self.IButtonInstance {},
	Next46: class extends self.IButtonInstance {},
	Next47: class extends self.IButtonInstance {},
	Next48: class extends self.IButtonInstance {},
	Next49: class extends self.IButtonInstance {},
	Next50: class extends self.IButtonInstance {},
	Katscene3: class extends self.ISpriteInstance {},
	Katscene4: class extends self.ISpriteInstance {},
	Next51: class extends self.IButtonInstance {},
	Next52: class extends self.IButtonInstance {},
	Next53: class extends self.IButtonInstance {},
	Next54: class extends self.IButtonInstance {},
	Next55: class extends self.IButtonInstance {},
	Next56: class extends self.IButtonInstance {},
	Next57: class extends self.IButtonInstance {},
	Next58: class extends self.IButtonInstance {},
	Next59: class extends self.IButtonInstance {},
	Next60: class extends self.IButtonInstance {},
	Katscene5: class extends self.ISpriteInstance {},
	Katscene6: class extends self.ISpriteInstance {},
	Next61: class extends self.IButtonInstance {},
	Next62: class extends self.IButtonInstance {},
	Next63: class extends self.IButtonInstance {},
	Next64: class extends self.IButtonInstance {},
	Next65: class extends self.IButtonInstance {},
	Next66: class extends self.IButtonInstance {},
	Next67: class extends self.IButtonInstance {},
	Next68: class extends self.IButtonInstance {},
	Next69: class extends self.IButtonInstance {},
	Next70: class extends self.IButtonInstance {},
	Katscene7: class extends self.ISpriteInstance {},
	BlackScreen3: class extends self.ISpriteInstance {},
	Katscene8: class extends self.ISpriteInstance {},
	Age: class extends self.IButtonInstance {},
	HeadScientist: class extends self.IButtonInstance {},
	Advisors: class extends self.IButtonInstance {},
	Stenabokovaya5: class extends self.ISpriteInstance {},
	NWjs: class extends self.IInstance {},
	Shkaf: class extends self.ISpriteInstance {},
	Polka2: class extends self.ISpriteInstance {},
	Polka3: class extends self.ISpriteInstance {},
	Table6: class extends self.ISpriteInstance {},
	Table7: class extends self.ISpriteInstance {},
	Photo: class extends self.IButtonInstance {},
	Crate: class extends self.IButtonInstance {},
	Documents: class extends self.IButtonInstance {},
	Boxes: class extends self.IButtonInstance {},
	Тач: class extends self.IInstance {},
	Photo1: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Ramka5: class extends self.ISpriteInstance {},
	Key1: class extends self.ISpriteInstance {},
	Key: class extends self.IButtonInstance {},
	Key2: class extends self.ISpriteInstance {},
	Backtogame: class extends self.IButtonInstance {},
	Leave2: class extends self.IButtonInstance {},
	HmzwNwczNwcz: class extends self.ISpriteInstance {},
	HmzwNwczNwczFace: class extends self.ISpriteInstance {},
	AdannButton: class extends self.IButtonInstance {},
	Room: class extends self.IButtonInstance {},
	BrokenAdann: class extends self.ISpriteInstance {},
	AdannBrokenFace: class extends self.ISpriteInstance {},
	Hmzw_Wvm_Admv: class extends self.ISpriteInstance {},
	Hmzw_Wvm_AdmvFace: class extends self.ISpriteInstance {},
	Close4: class extends self.IButtonInstance {},
	Computer: class extends self.ISpriteInstance {},
	Table8: class extends self.ISpriteInstance {},
	Ramka6: class extends self.ISpriteInstance {},
	SpriteNext1: class extends self.IButtonInstance {},
	SpriteNext2: class extends self.IButtonInstance {},
	SpriteBack: class extends self.IButtonInstance {},
	Katscene9: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	SpriteNext3: class extends self.IButtonInstance {},
	Face: class extends self.ISpriteInstance {},
	SpriteNext4: class extends self.IButtonInstance {},
	SpriteNext5: class extends self.IButtonInstance {},
	FilesSECRETROOM: class extends self.ISpriteInstance {},
	FileNext1: class extends self.IButtonInstance {},
	FileNext2: class extends self.IButtonInstance {},
	FileBack: class extends self.IButtonInstance {},
	FileNext3: class extends self.IButtonInstance {},
	FileNext4: class extends self.IButtonInstance {},
	FileNext5: class extends self.IButtonInstance {},
	FileNext6: class extends self.IButtonInstance {},
	Katscene21: class extends self.ISpriteInstance {},
	KatsceneSprite: class extends self.ISpriteInstance {},
	AdannSprite: class extends self.ISpriteInstance {},
	EchoSprite: class extends self.ISpriteInstance {},
	EchoFace: class extends self.ISpriteInstance {},
	KatsceneSprite2: class extends self.ISpriteInstance {},
	EchoSprite2: class extends self.ISpriteInstance {},
	AdannSprite2: class extends self.ISpriteInstance {},
	KatsceneSprite3: class extends self.ISpriteInstance {},
	AdannSprite3: class extends self.ISpriteInstance {},
	EchoSprite3: class extends self.ISpriteInstance {},
	KatsceneSprite4: class extends self.ISpriteInstance {},
	KatsceneSprite5: class extends self.ISpriteInstance {},
	EchoSprite4: class extends self.ISpriteInstance {},
	See: class extends self.ISpriteInstance {},
	KatsceneSprite6: class extends self.ISpriteInstance {},
	EchoSprite5: class extends self.ISpriteInstance {},
	KatsceneSprite7: class extends self.ISpriteInstance {},
	EchoSprite6: class extends self.ISpriteInstance {},
	Gone: class extends self.ISpriteInstance {},
	DoorBlocker29: class extends self.ISpriteInstance {},
	PressEdoor32: class extends self.ISpriteInstance {},
	EndKatscene: class extends self.ISpriteInstance {},
	BlackScreen4: class extends self.ISpriteInstance {},
	EchoSprite7: class extends self.ISpriteInstance {},
	SpriteNext6: class extends self.IButtonInstance {},
	KatsceneSprite8: class extends self.ISpriteInstance {},
	SpriteNext7: class extends self.IButtonInstance {},
	Локализация: class extends self.IInstance {},
	DeathKatscene1: class extends self.ISpriteInstance {},
	DeathKatscene2: class extends self.ISpriteInstance {},
	Reset: class extends self.IButtonInstance {},
	EndSprite: class extends self.ISpriteInstance {}
}